### ISSUE TITLE
have you covered HAproxy?

### ISSUE THREAD

**Issue by aglossa** [adam-p/adam-p.github.com#6]
In https://github.com/adam-p/adam-p.github.com/blob/master/content/blog/2022-02-26-x-forwarded-for.md did you analyze the behaviour of HAprxoxy (under the Redacted mentions?

Thank you for your analyse.

(in ingress of entreprise DMZ, our reverse proxy are removing XFF before adding their own one ; but we erred on the cautious side with explicit configuration. don't know what is HAproxy behavior with conf rules).

**Comment by adam-p** [comment]
I didn't cover it. I'll look at it a bit now and record some notes...

* With the `occ` param of the [`source` option](https://cbonte.github.io/haproxy-dconv/1.5/configuration.html#4.2-source) it allows for counting from the right. The default is to use the rightmost. (I can't pretend to understand this option by quickly reading it. Use XFF to bind a to a local address? Huh?)
* The [`forwardfor`](https://cbonte.github.io/haproxy-dconv/1.5/configuration.html#4.2-option%20forwardfor) option just appends to XFF. No interpretation.
* Some googling suggests that there's no automatic `X-Real-IP` thing. [Some people suggest](https://ypereirareis.github.io/blog/2019/06/04/real-client-ip-address-nginx-behind-haproxy-reverse-proxy/) adding it using `forwardfor`, which is safe (it's the socket IP your HAProxy is seeing). [Other people suggest](https://serverfault.com/a/722156/476142) getting the value from XFF, which is _not_ safe.

So, it _can_ be used safely, or it can be done wrong, but it doesn't do anything automatically. As far as I can see.
